# Generated by Django 5.2.7 on 2025-10-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='tarea',
            field=models.ManyToManyField(blank=True, to='alumnos.tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
